name   = Reitz Green
range  = 9-10
firetype     = reduction
by_vol    = n
component = Nepheline Syenite
amount    = 70
component = Petalite
amount    = 15
component = Whiting
amount    = 5
component = Ball Clay
amount    = 8
component = Gerstley Borate
amount    = 2
addition  = Rutile
addamount = 2
addition  = Cobalt Carbonate
addamount = 1
note = | Problems with pinholes -- try holding at 100-200F below top
